# netlify.toml

[build]
  # Directory to publish (e.g., your frontend build output)
  publish = "aimentor"

[functions]
  # Directory where your serverless functions are located
  directory = "netlify/functions/"

# You can specify the Python version for your functions
[functions."*"]
  runtime = "python3.12"
